export const condenser_api = {
  get_block: "condenser_api.get_block",
  get_dynamic_global_properties: "condenser_api.get_dynamic_global_properties",
};
export const database_api = {
  //TODO
};

// https://github.com/steemit/steem/blob/ff9b801615ba8c347a0c3f534ad06adc551b58e5/libraries/chain/include/steem/chain/steem_evaluator.hpp
export const operations = {
  account_create: "account_create",
  account_create_with_delegation: "account_create_with_delegation",
  account_update: "account_update",
  account_update2: "account_update2",
  transfer: "transfer",
  transfer_to_vesting: "transfer_to_vesting",
  witness_update: "witness_update",
  account_witness_vote: "account_witness_vote",
  account_witness_proxy: "account_witness_proxy",
  withdraw_vesting: "withdraw_vesting",
  set_withdraw_vesting_route: "set_withdraw_vesting_route",
  comment: "comment",
  comment_options: "comment_options",
  delete_comment: "delete_comment",
  vote: "vote",
  vote2: "vote2",
  custom: "custom",
  custom_json: "custom_json",
  custom_binary: "custom_binary",
  pow: "pow",
  pow2: "pow2",
  feed_publish: "feed_publish",
  convert: "convert",
  limit_order_create: "limit_order_create",
  limit_order_cancel: "limit_order_cancel",
  report_over_production: "report_over_production",
  limit_order_create2: "limit_order_create2",
  escrow_transfer: "escrow_transfer",
  escrow_approve: "escrow_approve",
  escrow_dispute: "escrow_dispute",
  escrow_release: "escrow_release",
  claim_account: "claim_account",
  create_claimed_account: "create_claimed_account",
  request_account_recovery: "request_account_recovery",
  recover_account: "recover_account",
  change_recovery_account: "change_recovery_account",
  transfer_to_savings: "transfer_to_savings",
  transfer_from_savings: "transfer_from_savings",
  cancel_transfer_from_savings: "cancel_transfer_from_savings",
  decline_voting_rights: "decline_voting_rights",
  reset_account: "reset_account",
  set_reset_account: "set_reset_account",
  claim_reward_balance: "claim_reward_balance",
  claim_reward_balance2: "claim_reward_balance2",
  delegate_vesting_shares: "delegate_vesting_shares",
  witness_set_properties: "witness_set_properties",
  smt_setup: "smt_setup",
  smt_setup_emissions: "smt_setup_emissions",
  smt_setup_ico_tier: "smt_setup_ico_tier",
  smt_set_setup_parameters: "smt_set_setup_parameters",
  smt_set_runtime_parameters: "smt_set_runtime_parameters",
  smt_create: "smt_create",
  smt_contribute: "smt_contribute",
  create_proposal: "create_proposal",
  update_proposal_votes: "update_proposal_votes",
  remove_proposal: "remove_proposal",
};
